e=eval(input("enter side  of cube\n"))
print("volume of cube is :",e*e*e)
f=eval(input("length of cuboid\n"))
g= eval (input("bredth of cuboid\n"))
h= eval (input("height of cuboid\n"))
print("volume of cuboid  is :",f*g*h)
i=eval(input("enter radius of cone\n"))
j=eval(input("enter height of cone\n"))
print("volume of cone  is :",1/3* pi*i*i*j)
